/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE bloqueBaseService PLEASE EDIT ../bloque.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
// DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Bloque } from '../../domain/giflo_db/bloque';
import { SessionService } from '../common/session.service';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Bloque.service.ts
 */

/*
 * SCHEMA DB Bloque
 *
	{
		direccion: {
			type: 'String'
		},
		nombre: {
			type: 'String'
		},
		orden: {
			type: 'Integer'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		bloque: {
			type: Schema.ObjectId,
			ref : "Nave"
		},
		empresa: {
			type: Schema.ObjectId,
			ref : "Bloque"
		},
		estado: {
			type: Schema.ObjectId,
			ref : "Bloque"
		},
	}
 *
 */
@Injectable()
export class BloqueBaseService {

    private bloqueCollection: AngularFirestoreCollection<Bloque>;
    private idEmpresa: string;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions,
        private session: SessionService
    ) {
        session.getUser().subscribe(ui => {
            if (ui) {
                this.idEmpresa = ui && ui.currentIdEmpresa ? ui.currentIdEmpresa : '-1';
                this.bloqueCollection = afs.collection<Bloque>('bloque', ref => ref.where('empresa', '==', this.idEmpresa));
            }
        });
    }


    // CRUD METHODS

    /**
    * BloqueService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Bloque): Promise<DocumentReference> {
        item.empresa = this.idEmpresa;
        return this.bloqueCollection.add(item);
    }

    /**
    * BloqueService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.bloqueCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * BloqueService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Bloque> {
        return this.afs.doc<Bloque>('bloque/' + id);
    }

    /**
    * BloqueService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Bloque[]> {
        return this.bloqueCollection.snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Bloque;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * BloqueService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Bloque>, item: Bloque): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
