/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE empresaBaseService PLEASE EDIT ../empresa.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
// DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Empresa } from '../../domain/giflo_db/empresa';
import { AngularFireAuth } from '@angular/fire/auth';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Empresa.service.ts
 */

/*
 * SCHEMA DB Empresa
 *
	{
		nombre: {
			type: 'String'
		},
		ruc: {
			type: 'String'
		},
		urlLogo: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		empresa: {
			type: Schema.ObjectId,
			ref : "Empleado"
		},
		empresa: {
			type: Schema.ObjectId,
			ref : "Bloque"
		},
		estado: {
			type: Schema.ObjectId,
			ref : "Empresa"
		},
		user: {
			type: Schema.ObjectId,
			ref : "Empresa"
		},
	}
 *
 */
@Injectable()
export class EmpresaBaseService {
    private empresaCollection: AngularFirestoreCollection<Empresa>;
    private listUser: Observable<Empresa[]>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions,
        public afAuth: AngularFireAuth
    ) {
        this.empresaCollection = afs.collection<Empresa>('empresa');
        this.listUser = new Observable<Empresa[]>(observer => {
            this.afAuth.user.subscribe(user => {
                if (user) {
                    this.afs.collection('empresa', ref => ref.where('user', '==', user.uid)).snapshotChanges().pipe(
                        map(actions => actions.map(a => {
                            const data = a.payload.doc.data() as Empresa;
                            const id = a.payload.doc.id;
                            return { id, ...data };
                        }))
                    ).subscribe(array => observer.next(array));
                } else {
                    observer.next([]);
                }
            });
        });
    }


    // CRUD METHODS

    /**
    * EmpresaService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Empresa): Promise<DocumentReference> {
        return this.empresaCollection.add(item);
    }

    /**
    * EmpresaService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.empresaCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * EmpresaService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Empresa> {
        return this.afs.doc<Empresa>('empresa/' + id);
    }

    /**
    * EmpresaService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Empresa[]> {
        return this.afs.collection('empresa').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Empresa;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * EmpresaService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Empresa>, item: Empresa): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

    listByUser(): Observable<Empresa[]> {
        return this.listUser;
    }

}
