/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE estadoBaseService PLEASE EDIT ../estado.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
// DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Estado } from '../../domain/giflo_db/estado';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Estado.service.ts
 */

/*
 * SCHEMA DB Estado
 *
	{
		nombre: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		activo: {
			type: Schema.ObjectId,
			ref : "Rol"
		},
		estado: {
			type: Schema.ObjectId,
			ref : "Empresa"
		},
		estado: {
			type: Schema.ObjectId,
			ref : "Empleado"
		},
		estado: {
			type: Schema.ObjectId,
			ref : "Bloque"
		},
		estado: {
			type: Schema.ObjectId,
			ref : "Cama"
		},
		estado: {
			type: Schema.ObjectId,
			ref : "Nave"
		},
		estado: {
			type: Schema.ObjectId,
			ref : "Pagina"
		},
	}
 *
 */
@Injectable()
export class EstadoBaseService {

    private estadoCollection: AngularFirestoreCollection<Estado>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.estadoCollection = afs.collection<Estado>('estado');
        this.list().subscribe((estados: Estado[]) => {
            if (estados.length === 0) {
                let item: Estado = { id: 'ACT', nombre: 'ACTIVO' };
                this.create(item);
                item = { id: 'INAC', nombre: 'INACTIVO' };
                this.create(item);
            }
        });
    }


    // CRUD METHODS

    /**
    * EstadoService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Estado): Promise<void> {
        return this.estadoCollection.doc(item.id).set(item);
    }

    /**
    * EstadoService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.estadoCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * EstadoService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Estado> {
        return this.afs.doc<Estado>('estado/' + id);
    }

    /**
    * EstadoService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Estado[]> {
        return this.afs.collection('estado').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Estado;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * EstadoService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Estado>, item: Estado): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
