/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE estado-civilBaseService PLEASE EDIT ../estado-civil.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { EstadoCivil } from '../../domain/giflo_db/estado-civil';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../EstadoCivil.service.ts
 */

/*
 * SCHEMA DB EstadoCivil
 *
	{
		nombre: {
			type: 'String'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class EstadoCivilBaseService {

    private estadocivilCollection: AngularFirestoreCollection<EstadoCivil>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.estadocivilCollection = afs.collection<EstadoCivil>('estadocivil');
    }


    // CRUD METHODS

    /**
    * EstadoCivilService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: EstadoCivil): Promise<DocumentReference> {
        return this.estadocivilCollection.add(item);
    }

    /**
    * EstadoCivilService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.estadocivilCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * EstadoCivilService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<EstadoCivil> {
        return this.afs.doc<EstadoCivil>('estadocivil/' + id);
    }

    /**
    * EstadoCivilService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<EstadoCivil[]> {
        return this.afs.collection('estadocivil').snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as EstadoCivil;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * EstadoCivilService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<EstadoCivil>, item: EstadoCivil): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
