/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE menu-itemBaseService PLEASE EDIT ../menu-item.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
// DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG

// MODEL
import { MenuItem } from '../../domain/giflo_db/menu-item';
import { AngularFireAuth } from '@angular/fire/auth';
import { SessionService } from '../session.service';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../MenuItem.service.ts
 */

/*
 * SCHEMA DB MenuItem
 *
	{
		estado: {
			type: 'Boolean'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		pagina: {
			type: Schema.ObjectId,
			ref : "MenuItem"
		},
		rol: {
			type: Schema.ObjectId,
			ref : "MenuItem"
		},
	}
 *
 */
@Injectable()
export class MenuItemBaseService {

    private menuitemCollection: AngularFirestoreCollection<MenuItem>;
    private lisMenuUser: Observable<any>;
    private idEmpresa: string;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions,
        private afAuth: AngularFireAuth,
        private session: SessionService
    ) {
        session.getUserInfo().subscribe(ui => {
            this.idEmpresa = ui ? ui.idEmpresa : '-1';
            this.menuitemCollection = afs.collection<MenuItem>('menuitem',
                ref => ref.where('empresa', '==', ui ? ui.idEmpresa : '-1'));
        });
    }


    // CRUD METHODS

    /**
    * MenuItemService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: MenuItem): Promise<DocumentReference> {
        item.empresa = this.idEmpresa;
        return this.menuitemCollection.add(item);
    }
    createCustom(item: MenuItem): Promise<DocumentReference> {
        item.empresa = null;
        return this.menuitemCollection.add(item);
    }

    /**
    * MenuItemService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.menuitemCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * MenuItemService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<MenuItem> {
        return this.afs.doc<MenuItem>('menuitem/' + id);
    }

    /**
    * MenuItemService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<MenuItem[]> {
        return this.menuitemCollection.snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as MenuItem;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * MenuItemService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<MenuItem>, item: MenuItem): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
