/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE naveBaseService PLEASE EDIT ../nave.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
// DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Nave } from '../../domain/giflo_db/nave';
import { SessionService } from '../session.service';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Nave.service.ts
 */

/*
 * SCHEMA DB Nave
 *
	{
		nombre: {
			type: 'String'
		},
		orden: {
			type: 'Integer'
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		bloque: {
			type: Schema.ObjectId,
			ref : "Nave"
		},
		estado: {
			type: Schema.ObjectId,
			ref : "Nave"
		},
		nave: {
			type: Schema.ObjectId,
			ref : "Cama"
		},
	}
 *
 */
@Injectable()
export class NaveBaseService {

    private idEmpresa: string;
    private naveCollection: AngularFirestoreCollection<Nave>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions,
        private session: SessionService
    ) {
        session.getUser().subscribe(ui => {
            this.idEmpresa = ui && ui.currentIdEmpresa ? ui.currentIdEmpresa : '-1';
            this.naveCollection = afs.collection<Nave>('nave', ref => ref.where('empresa', '==', this.idEmpresa));
        });
    }


    // CRUD METHODS

    /**
    * NaveService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Nave): Promise<DocumentReference> {
        item.empresa = this.idEmpresa;
        return this.naveCollection.add(item);
    }

    /**
    * NaveService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.naveCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * NaveService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Nave> {
        return this.afs.doc<Nave>('nave/' + id);
    }

    /**
    * NaveService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Nave[]> {
        return this.naveCollection.snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Nave;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * NaveService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Nave>, item: Nave): Promise<void> {
        return itemDoc.update(item);
    }


    // Custom APIs

}
