/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE empleadoBaseService PLEASE EDIT ../empleado.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
// DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { AngularFirestore, AngularFirestoreDocument, AngularFirestoreCollection, DocumentReference } from '@angular/fire/firestore';
import { AngularFireFunctions } from '@angular/fire/functions';

// CONFIG

// MODEL
import { Persona } from 'src/app/domain/giflo_db/persona';


@Injectable()
export class PersonaBaseService {

    private empleadoCollection: AngularFirestoreCollection<Persona>;
    constructor(
        private afs: AngularFirestore,
        private fns: AngularFireFunctions
    ) {
        this.empleadoCollection = afs.collection<Persona>('persona');
    }
    // CRUD METHODS

    /**
    * EmpleadoService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Persona): Promise<DocumentReference> {
        return this.empleadoCollection.add(item);
    }
    createCustom(item: Persona): Promise<void> {
        return this.empleadoCollection.doc(item.id).set(item);
    }

    /**
    * EmpleadoService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string) {
        const itemDoc: AngularFirestoreDocument<any> = this.empleadoCollection.doc(id);
        itemDoc.delete();
    }

    /**
    * EmpleadoService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id 
    *
    */
    get(id: string): AngularFirestoreDocument<Persona> {
        return this.afs.doc<Persona>('persona/' + id);
    }

    /**
    * EmpleadoService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Persona[]> {
        return this.empleadoCollection.snapshotChanges().pipe(
            map(actions => actions.map(a => {
                const data = a.payload.doc.data() as Persona;
                const id = a.payload.doc.id;
                return { id, ...data };
            }))
        );
    }

    /**
    * EmpleadoService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(itemDoc: AngularFirestoreDocument<Persona>, item: Persona): Promise<void> {
        return itemDoc.update(item);
    }
    // Custom APIs

}
