/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE produccionBase PLEASE EDIT ../produccion.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */

import { Empleado } from '../empleado';
import { DiaTrabajo } from '../dia-trabajo';
import { Variedad } from '../variedad';
import { Cama } from '../cama';
import { Nave } from '../nave';
import { Bloque } from '../bloque';
import { Empresa } from '../empresa';

/**
 * This is the model of produccion object
 *
 */
export interface ProduccionBase {

    id: string;
    cantidad?: number;
    estado?: string;
    bloque?: Bloque | string;
    nave?: Nave | string;
    cama?: Cama | string;
    variedad?: Variedad | string;
    dia_trabajo?: DiaTrabajo | string;
    supervisor: Empleado | string;
    // Relations trabajador
    trabajador: Empleado | string;
    empresa: Empresa | string;
}
