/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE VariedadBase PLEASE EDIT ../variedad.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */

import { User } from '../user';
import { MenuItem } from '../menu-item';
import { Empresa } from '../empresa';

/**
 * This is the model of Variedad object
 *
 */
export interface UserDataBase {
    user?: User;
    menu?: MenuItem[];
    currentCompany?: Empresa;
    offline?: boolean;
    hasAllOptions?: boolean;
    idEmpleado?: string;
    idEmpresa?: string;
    tipo?: string;
}
