/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE UserBase PLEASE EDIT ../user.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Direccion } from '../direccion';
import { Estado } from '../estado';
import { EstadoCivil } from '../estado-civil';

/**
 * This is the model of User object
 *
 */
export interface UserBase {

    id: string;
    roles?: string[];
    nombres?: string;
    apellidos?: string;
    fechaNacimiento?: Date;
    identificacion?: string;
    tipoIdentificacion?: string;
    urlFoto?: string;
    celular?: string;
    email?: string;
    paginaWeb?: string;
    telefono?: string;
    urlFacebook?: string;
    // Relations direccion
    direcciones?: Direccion[];
    // Relations estado
    estado?: Estado | string;
    // Relations estadoCivil
    estadoCivil?: EstadoCivil | string;
    currentIdEmpresa?: string;
    currentEmpresa?: string;
    currentEmpleado?: string;
    currentTipo?: string;
}
